name: Azure x86 Graal latest
on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Image version (x.x.x)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v5


      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: '1.11.2'

      - name: Init Packer
        run: cd packer; packer init azure-x86-graal.pkr.hcl

        # run: packer plugins install github.com/hashicorp/azure && packer plugins install github.com/hashicorp/ansible

      - name: Build image from template
        run: ./build-azure-x86-graal.sh  --java-major 25 --graalvm-version 25.0.0 --client-id "${{ secrets.AZURE_CLIENT_ID }}" --client-secret "${{ secrets.AZURE_CLIENT_SECRET }}" --subscription-id "${{ secrets.AZURE_SUBSCRIPTION_ID }}" --tenant-id "${{ secrets.AZURE_TENANT_ID }}" --image-version "${{ github.event.inputs.image_version }}"
