name: GCP x86 java latest
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install `ansible bundle`
        run: pip install ansible jmespath

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Install `packer plugins - GCP`
        run: packer plugins install github.com/hashicorp/googlecompute

      - name: Install `packer plugins - Ansible`
        run: packer plugins install github.com/hashicorp/ansible

      - name: Configure GCP Credentials
        run: |
          echo $ENV_FILE > creds.json;
        shell: bash
        env: 
          ENV_FILE: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} 

      - name: Build image from template
        run: export GOOGLE_APPLICATION_CREDENTIALS="./creds.json";  ./build-gcp-x86-zulu.sh  --java-major 25 --project-id "${{ secrets.GOOGLE_PROJECT_ID }}" --latest true
